package com.lee.runrouter.dbconnection.queries;

import com.lee.runrouter.bbcalculator.BBCalculator;
import com.lee.runrouter.bbcalculator.ScaledBBCalculator;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class WayQueryDirectorTest {
    QueryDirector qd;
    BBCalculator calc;
    QueryBuilder qb;

    private final String SELECT_ID_TAGS_NODES = "SELECT w.id, w.tags, w.nodes, \n";
    private final String SELECT_LENGTH = "\tST_Length(l.way::geography) AS length, \n";
    private final String SELECT_CORDS = "\tST_AsText(l.way) AS coords, \n";
    private final String SELECT_START_ELEVATION = "\t(SELECT ST_Value(rast, ST_SetSRID(ST_StartPoint(l.way),4326)) as startElevation\n" +
            "\tFROM elevation\n" +
            "\tWHERE ST_Intersects(rast, ST_SetSRID(ST_StartPoint(l.way),4326))), \n";
    private final String SELECT_END_ELEVATION = "\t(SELECT ST_Value(rast, ST_SetSRID(ST_EndPoint(l.way),4326)) as endElevation \n" +
            "\tFROM elevation\n" +
            "\tWHERE ST_Intersects(rast, ST_SetSRID(ST_EndPoint(l.way),4326))) \n";
    private final String FROM = "\tFROM planet_osm_ways w, planet_osm_line l \n";
    private final String JOIN = "\tWHERE l.osm_id = w.id\n";
    private final String BB = "\tAND l.way && ST_Transform( ST_MakeEnvelope(?,?,?,?, 4326),4326)\n";
    private final String ROAD_OPTIONS = "\tAND (l.highway IN ('trunk', 'primary', 'secondary', 'tertiary'," +
            " 'unclassified', 'residential', 'living_street', 'service'," +
            " 'pedestrian', 'track', 'road', 'footway', 'bridleway', 'steps', 'path')) \n";
    private final String END = "\tAND (l.foot <> 'no' OR l.foot IS NULL)";
    private String sql;

    @Before
    public void setUp() {
        qb = new WayQueryBuilder();
        calc = new ScaledBBCalculator();
        qd = new WayQueryDirector(qb, calc);

        sql = SELECT_ID_TAGS_NODES + SELECT_LENGTH + SELECT_CORDS +
                SELECT_START_ELEVATION + SELECT_END_ELEVATION + FROM + JOIN;
    }

    @Test
    public void testPreparedStatementCoordsCorrectOne() {
        qd.buildQuery(50, 0, 5);
        double[] BBCords = calc.calcBoundingBox(50, 0, 5);

        String newBB = String.format("\tAND l.way && ST_Transform( ST_MakeEnvelope(%s,%s,%s,%s, 4326),4326)\n",
                BBCords[0], BBCords[1], BBCords[2], BBCords[3]);

        sql += newBB + ROAD_OPTIONS + END;

        assertEquals(sql, qd.ps.toString()); // Assert the query string generated by the query director is
        // equal to the required query string
    }

    @Test
    public void testPreparedStatementCoordsCorrectTwo() {
        qd.buildQuery(25, 0, 0.2);
        double[] BBCords = calc.calcBoundingBox(25, 0, 0.2);

        String newBB = String.format("\tAND l.way && ST_Transform( ST_MakeEnvelope(%s,%s,%s,%s, 4326),4326)\n",
                BBCords[0], BBCords[1], BBCords[2], BBCords[3]);

        sql += newBB + ROAD_OPTIONS + END;

        assertEquals(sql, qd.ps.toString()); // Assert the query string generated by the query director is
        // equal to the required query string
    }

    @Test
    public void testPreparedStatementOptionsCorrectOne() {

        double[] BBCords = calc.calcBoundingBox(50, 0, 5);

        qd.setOptions(new boolean[] {true, false, false, false, false, false, false, false, false,
                false, false, false, false, true, true}); // set the new options
        qd.buildQuery(50, 0, 5);


        String newBB = String.format("\tAND l.way && ST_Transform( ST_MakeEnvelope(%s,%s,%s,%s, 4326),4326)\n",
                BBCords[0], BBCords[1], BBCords[2], BBCords[3]);

        String newRoadOptions = "\tAND (l.highway IN ('trunk', '', '', ''," +
                " '', '', '', '', '', '', '', '', '', 'steps', 'path')) \n";

        sql += newBB + newRoadOptions + END;

        assertEquals(sql, qd.ps.toString()); // Assert the query string generated by the query director is
        // equal to the required query string
    }


    @Test
    public void testPreparedStatementOptionsCorrectTwo() {

        double[] BBCords = calc.calcBoundingBox(50, 0, 5);

        qd.setOptions(new boolean[] {false, false, false, false, false, false, false, false, false,
                false, false, false, false, false, false}); // set the new options
        qd.buildQuery(50, 0, 5);


        String newBB = String.format("\tAND l.way && ST_Transform( ST_MakeEnvelope(%s,%s,%s,%s, 4326),4326)\n",
                BBCords[0], BBCords[1], BBCords[2], BBCords[3]);

        String newRoadOptions = "\tAND (l.highway IN ('', '', '', ''," +
                " '', '', '', '', '', '', '', '', '', '', '')) \n";

        sql += newBB + newRoadOptions + END;

        assertEquals(sql, qd.ps.toString()); // Assert the query string generated by the query director is
        // equal to the required query string
    }
}